### ISSUE TITLE
Homework finished

### ISSUE THREAD

**Issue by renestadler** [htl-perg-2019-20-5bhif/highscore-exercise-renestadler#5]
Dear Mr Stropek!

@michaelhitzker and I have completed the homework and want to gain all six points.

The information for the docker-building can be found in the readme-docker.md file,
the API is hosted at following URL:
http://highscoresample-api.azurewebsites.net/

The Frontend is hosted at following UI:
http://highscoresample.azurewebsites.net/

The rest of the tasks can be found in the GIT-Repository.

Kind Regards,
René Stadler
Michael Hitzker

**Comment by rstropek** [comment]
That is SO AWESOME 🤩. Love the way you display the highscore list and let me enter my initials. Very well done 👍👍!
